---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	detect(detect)
	noise(noise)
	cause(cause)
	cause_retry(cause_retry)
	supervisor(supervisor)
	impact(impact)
	fast_impact(fast_impact)
	response(response)
	__end__([<p>__end__</p>]):::last
	__start__ --> detect;
	cause -.-> cause_retry;
	cause -.-> supervisor;
	cause_retry --> supervisor;
	detect -.-> cause;
	detect -.-> noise;
	fast_impact --> response;
	impact --> response;
	supervisor -.-> fast_impact;
	supervisor -.-> impact;
	noise --> __end__;
	response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
